version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    pull_policy: build
    command: gunicorn openloop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - stack.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - stack.env
  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    pull_policy: build
    volumes:
      - node_modules:/app/www/node_modules
    expose:
      - 3000
    depends_on:
      - web
  nginx:
    build: ./nginx
    pull_policy: build
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
      - www
volumes:
  media_volume:
  node_modules:
  postgres_data:
  static_volume:
